/**
 * RFC9457: Problem Details for HTTP APIs
 * @see https://www.rfc-editor.org/rfc/rfc9457.html
 *
 * This module defines types and utilities for RFC9457-compliant error responses.
 */

/**
 * RFC9457 Problem Details object
 *
 * A machine-readable format for specifying errors in HTTP API responses.
 */
export interface ProblemDetails {
  /**
   * A URI reference (RFC3986) that identifies the problem type.
   * When dereferenced, it SHOULD provide human-readable documentation for the problem type.
   * Default: "about:blank"
   */
  type: string;

  /**
   * A short, human-readable summary of the problem type.
   * It SHOULD NOT change from occurrence to occurrence of the problem.
   */
  title: string;

  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  status: number;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail: string;

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   * It may or may not yield further information if dereferenced.
   */
  instance?: string;

  /**
   * Additional extension members
   * Problem type definitions MAY extend the problem details object with additional members.
   */
  [key: string]: any;
}

/**
 * Option type for creating a ProblemDetails object
 */
export interface CreateProblemDetailsOptions {
  type?: string;
  title: string;
  status: number;
  detail: string;
  instance?: string;
  extensions?: Record<string, any>;
}

/**
 * The media type for RFC9457 problem details
 */
export const PROBLEM_DETAILS_MEDIA_TYPE = 'application/problem+json' as const;

/**
 * Default type URI for generic problems
 */
export const DEFAULT_PROBLEM_TYPE = 'about:blank' as const;