/**
 * Config Types Generator
 * 
 * Generates config/types.ts from discovered configuration files.
 */

import { readdirSync, existsSync } from 'fs';
import { join, basename, extname } from 'path';
import { FileGenerator } from './FileGenerator';

export class ConfigTypesGenerator extends FileGenerator {
  constructor(private readonly configPath: string) {
    super();
  }

  async execute(): Promise<void> {
    if (!existsSync(this.configPath)) {
      console.warn(`[Generator] Config directory not found: ${this.configPath}`);
      return;
    }

    const files = readdirSync(this.configPath);
    
    // Filter for .ts files (excluding .d.ts, test files, $types.ts, and index.ts)
    const configFiles = files
      .filter((file) => {
        const ext = extname(file);
        const baseName = basename(file, '.ts');
        return (
          ext === '.ts' &&
          !file.endsWith('.d.ts') &&
          !file.endsWith('.test.ts') &&
          !file.endsWith('.spec.ts') &&
          baseName !== 'README' &&
          baseName !== 'types' &&
          baseName !== 'index' && // Exclude index.ts (re-export file)
          !baseName.startsWith('$') // Exclude auto-generated files
        );
      })
      .map((file) => basename(file, '.ts'));

    if (configFiles.length === 0) {
      console.warn('[Generator] No config files found');
      return;
    }

    const content = this.generateContent(configFiles);
    const typesPath = join(this.configPath, '$types.ts');

    this.generate({
      path: typesPath,
      content,
      overwrite: true,
    });
  }

  private generateContent(configFiles: string[]): string {
    // Generate type names (capitalize first letter)
    const typeNames = configFiles.map(
      (file) => `${file.charAt(0).toUpperCase() + file.slice(1)}Config`,
    );

    return `/**
 * Configuration Type Definitions
 *
 * ⚠️ AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is automatically generated by ConfigTypesGenerator.
 * The $ prefix indicates this file is auto-generated.
 *
 * To regenerate: npm run artisan generate:config-types
 *
 * Types are automatically inferred from Zod schemas in individual config files.
 */

${configFiles
  .map((file, i) => `import type { ${typeNames[i]} } from './${file}';`)
  .join('\n')}

/**
 * Re-export individual config types
 */
export type { ${typeNames.join(', ')} };

/**
 * Complete Application Configuration Interface
 */
export interface Config {
${configFiles.map((file, i) => `  ${file}: ${typeNames[i]};`).join('\n')}
}

/**
 * Type-safe configuration paths for autocomplete
 */
export type ConfigPaths =
${configFiles.map((file) => `  | '${file}'\n  | \`${file}.\${string}\``).join('\n')};
`;
  }
}